### ISSUE TITLE
Sign in button not firing a click event

### ISSUE THREAD

**Issue by VR-Architect** [AvantiPoint/mobileauth-lib#2]
Hi,
Just downloaded and ran, when debugging with Win, the clicking of the sign in buttons didn't result in anything happening.  The image was not in a position like in your video, it was spaced over top of the buttons, so I hide the image and tried again. Still the clicking of the buttons didn't result in anything or run any code on click as far as I can tell. 

Thanks

**Comment by dansiegel** [comment]
This is not an actionable issue. I have no screen shots. I assume you're talking about the sample project which works fine on my machine.
