### ISSUE TITLE
Signout throws exception when called

### ISSUE THREAD

**Issue by meron1122** [AvantiPoint/mobileauth-lib#6]
When i call `signout` endpoint, and i logged via google, i received exception:

> System.InvalidOperationException: The authentication handler registered for scheme 'Google' is 'GoogleHandler' which cannot be used for SignOutAsync. The registered sign-out schemes are: Cookies.

I don't know, is miss configuration for my side?

**Comment by dansiegel** [comment]
looking more at this, I believe it's an oversight in the library that is causing this bug. I should have a fix out in the next week.

**Comment by dansiegel** [comment]
A fix for this has been introduced in 0.2.6. A new Token Store has been introduced to manage valid tokens. By default this should generate a file store to manage it. You can provide your own implementation and store the tokens in an existing database.
